[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_18", "nginx", "mysql"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install --legacy-peer-deps" # أو احذفها لو ما عندك frontend
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan view:cache",
  "php artisan route:cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
